# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# markdown: kramdown

title: afei's coffee shop
email: neocxf@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A honst man that love programming. An enthusiasm man that love NBA and specifically King James.
  #StriveForGreatness
  #Peace
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: neocxf
github_username:  afeish
author: Fei Chen

# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-jupyter-notebook

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

breadcrumbs: true  # disabled by default
breadcrumb_home_label : "Start"
breadcrumb_separator  : ">"

search: true
search_full_content: true
lunr:
  search_within_pages: true

jupyter_notebook:
  content: body
  prompt: true

# search_provider: algolia
# algolia:
#   application_id: W8KRYVGEHX
#   index_name: afeish # YOUR_INDEX_NAME
#   search_only_api_key: 34c061b6c2cd87a8e6cbf4dbd54323c7
#   powered_by: true # true (default), false


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# paginate_path: /blog/page:num

include:
  - _pages

defaults:
  - scope:
      path: "assets/logos"
    values:
      image: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: tag
    values:
      author_profile: true
  - scope:
      path: ""
      type: category
    values:
      comments: true

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  archives:
    output: true
    permalink: /archives/:path/

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/

jekyll-archives:
  enabled: all
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
    year: archive-taxonomy
    month: archive-taxonomy
    day: archive-taxonomy
    # year: year-archive
    # month: month-archive
    # day: day-archive
    # category: category-archive
    # tag: tag-archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    day: '/archives/:year/:month/:day/'


compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment


repository: afeish/afeish.github.io
comments:
  provider: "giscus"
  giscus:
    repo_id              : R_kgDOLenvDw
    category_name        : Announcements # Full text name of the category
    category_id          : DIC_kwDOLenvD84Cd8iw # Shown during giscus setup at https://giscus.app
    discussion_term      : pathname # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : 1 # '1' for enabled (default), '0' for disabled
    theme                : preferred_color_scheme # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
